services:
  - type: web
    name: estoque-flask
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    region: oregon